# Default configuration for GCDM
project:
  name: gcdm-ct
  seed: 42
  processes: 4

region:
  focus_state_fips: "09"  # CT
  airports: [HVN, JFK, LGA, EWR]
  modes: [drive, ride, rail]

party:
  NA: 1
  NC: 0
  vA_usd_per_hour: 18.0
  vC_usd_per_hour: 9.0
  lambda_child_time_weight: 0.5

schedule:
  t_depart_iso: "2025-09-13T09:00:00-04:00"
  curb_windows:
    HVN: { tmin: "2025-09-13T09:45:00-04:00", tmax: "2025-09-13T11:00:00-04:00" }
    JFK: { tmin: "2025-09-13T11:00:00-04:00", tmax: "2025-09-13T13:00:00-04:00" }
    LGA: { tmin: "2025-09-13T10:30:00-04:00", tmax: "2025-09-13T12:30:00-04:00" }
    EWR: { tmin: "2025-09-13T11:00:00-04:00", tmax: "2025-09-13T13:00:00-04:00" }

vot:
  tod_bands:
    - { name: night, minutes_value: 0.25 }
    - { name: offpeak, minutes_value: 0.30 }
    - { name: peak, minutes_value: 0.45 }
  peak_hours: [7,8,9,16,17,18]

risk:
  alpha: 0.9
  rho: 0.5
  multipliers:
    weather: 1.0
    event: 1.0
    construction: 1.0
  shocks:
    incident_prob: 0.05
    incident_minutes: 15
    rail_disruption_prob: 0.03
    rail_disruption_minutes: 25

modes:
  drive:
    cost:
      cmile: 0.65
      tolled_miles_multiplier: 1.0
      rem_lot_fee: 0.0
      shuttle_fee: 0.0
      fare_risk: 2.0
    parking_daily:
      HVN: 15.0
      JFK: 45.0
      LGA: 45.0
      EWR: 40.0
    parking_weekly:
      HVN: 70.0
      JFK: 240.0
      LGA: 240.0
      EWR: 220.0
  ride:
    surge: 1.0
    base_fare: 2.50
    per_mile: 2.00
    per_minute: 0.40
    booking_fee: 2.75
    tip_fraction: 0.15
    fare_risk: 3.0
  rail:
    adult_fare_default: 18.0
    child_fare_default: 9.0
    transfer_fare: 2.90
    airtrain:
      JFK: 8.50
      EWR: 8.25
      HVN: 0.0
      LGA: 0.0
    station_parking: 5.0
    miss_prob_base: 0.10
    headway_minutes: 15
    miss_slope: 0.02

process_times:
  security_mean:
    HVN: 10
    JFK: 25
    LGA: 20
    EWR: 25
  bag_drop_mean:
    none: 0
    carryon: 0
    checked: 10
  walk_mean:
    HVN: 6
    JFK: 15
    LGA: 12
    EWR: 15

comfort:
  omega_peak: 1.35
  omega_night: 1.25
  omega_drive_rain: 1.15
  omega_rail_crowd: 1.10

carbon:
  enabled: true
  social_cost_per_ton: 56.0
  emissions_kg_per_mile:
    drive: 0.404
    ride: 0.404
    rail: 0.09

softmin:
  mu: 0.15

map:
  output_crs: 3857
  interactive: true
  basemap: "contextily"
  title: "Generalized-Cost Delta Map (HVN vs. JFK/LGA/EWR)"

providers:
  enable_google: true
  enable_openrouteservice: true
  enable_weather: true
  enable_events: true
  google_api_key: ""
  ors_api_key: ""
  owm_api_key: ""
  ticketmaster_api_key: ""
  enable_mapbox: true
  mapbox_api_key: ""

qsi:
  muA: 0.2
  betaA: 0.03
  betaD: 0.02
  betaV: 0.01
  betaW: 0.02
  betaC: 0.02
  beta_rec: 0.02
  xi: 0.15
  betaQ: 0.02
  quality_weights: { wseat: 0.5, wwifi: 0.2, wac: 0.2, wprio: 0.1 }
  beta_ffp: 0.01
  beta_lounge: 0.01
  beta_pre: 0.01
  beta_scar: 0.02
  beta_B: 0.02
  bank_window_w: 1.0
  beta_MCT: 0.03
  beta_bag: 0.02
  alt_window_minutes: 180
  share_theta: 1.0
  states:
    - { name: base, weight: 0.6, price_multiplier: 1.0, delay_mean_add: 0, delay_var_mult: 1.0 }
    - { name: peak, weight: 0.3, price_multiplier: 1.05, delay_mean_add: 10, delay_var_mult: 1.2 }
    - { name: storm, weight: 0.1, price_multiplier: 1.15, delay_mean_add: 30, delay_var_mult: 1.6 }
  segments:
    - { name: domestic, weight: 0.6, beta_P: 0.01, p_star: 250, seats_threshold: 4 }
    - { name: intl, weight: 0.4, beta_P: 0.008, p_star: 600, seats_threshold: 2 }
  dests:
    - { code: ORD, weight: 0.15 }
    - { code: ATL, weight: 0.15 }
    - { code: CLT, weight: 0.15 }
    - { code: DFW, weight: 0.1 }
    - { code: LAX, weight: 0.1 }
    - { code: SFO, weight: 0.1 }
    - { code: LHR, weight: 0.1 }
    - { code: CDG, weight: 0.05 }
    - { code: FRA, weight: 0.05 }
  hub_risks:
    CLT: { WxRisk: 0.2, CapacityRisk: 0.3, MCT: 40, bank_times: ["08:00", "12:00", "17:00", "21:00"] }
    ATL: { WxRisk: 0.25, CapacityRisk: 0.35, MCT: 45, bank_times: ["09:00", "13:00", "18:00", "22:00"] }
    ORD: { WxRisk: 0.35, CapacityRisk: 0.4, MCT: 45, bank_times: ["08:30", "12:30", "17:30", "21:30"] }

